### ISSUE TITLE
add directory for non-rendered markdowns

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/quarto-course-template#1]
In case developers want to omit some files from rendering, add to `_quarto.yml` (last line):

 ```yml
project:
  type: website
  output-dir: _site
  render:
    - index.md
    - setup.md
    - materials.md
    - materials/*
    - "!materials/*/_no-render"
```

Will also need to add documentation about this.
