### ISSUE TITLE
version history

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/quarto-course-template#14]
For courses where we want to keep history. 

Running some tests with a mixture of github actions and gh releases. 

Can try adding this automatically into the `_quarto.yml`: 

```yml
    left:
      - text: "Version"
        icon: clock-history
        menu: 
          - text: "2023-01-01"
          - text: "2023-02-01"
```
