### ISSUE TITLE
Updates to `_quarto.yml` after upgrading

### ISSUE THREAD

**Issue by mvanrongen** [cambiotraining/quarto-course-template#20]
**Updates to the documentation:**

When upgrading from an older version, the `_quarto.yml` file needs manual adjusting:

```
exercises:
  number: true
  hide-answers: false

filters:
  - courseformat
```

Additionally, the `courseformat` folder is apparently stored directly in `_extensions` instead of `_extensions/cambiotraining`, which means that the links to the icons need updating, if moving from an older template version.
