### ISSUE TITLE
Auto dark mode extension

### ISSUE THREAD

**Issue by mvanrongen** [cambiotraining/quarto-course-template#21]
I've added an [auto dark mode extension](http://pkg.garrickadenbuie.com/quarto-auto-dark/#example) to my in-progress [coding for research](https://cambiotraining.github.io/coding-for-research/) materials.

Works quite well out-of-the-box. Two changes in `_quarto.yml`, an added filter and an added theme:

```
filters:
  - courseformat
  - auto-dark

format:
  courseformat-html:
    theme: flatly
```

edit:

Needs a tweak in the extension itself, because otherwise the background colour of the sourceCode blocks is also black. This makes it hard to see the delineation of the code chunks. In the `auto-dark-mode.css` file, add:

```
  /* Re-enable source code block backgrounds. */
  div.sourceCode {
    filter: invert(10%);
  }
```
