### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by mvanrongen** [cambiotraining/quarto-course-template#22]
Quarto now has [Lighbox](https://quarto.org/docs/output-formats/html-lightbox-figures.html) available by default. The feature I find useful here is that, when you click on an image, it then pops out and you can see it full view.

I suggest enabling it by default in `_quarto.yml`:

```
format:
  courseformat-html:
    theme: flatly
    lightbox: true
```
