### ISSUE TITLE
Can navbar be defined from within `materials` directory?

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/quarto-course-template#3]
Can the `navbar` and `sidebar` be defined from an `index.md` file in the `materials/` directory? 
This way we can keep the navigation setup separate from the main `_quarto.yml` file. 

This would also be an alternative to [sidebar auto generation](https://quarto.org/docs/websites/website-navigation.html#auto-generation), which might be inconvenient in some cases.

**Comment by tavareshugo** [comment]
Yes it can.

- Add the following to _quarto.yml:
  ```yml
  metadata-files:
    - "materials/_sidebar.yml"
  ```
- Then create the file `materials/_sidebar.yml` with the sidebar specification only (this shouldn't be in the main `_quarto.yml` file anymore):
  ```yml
  website:
    sidebar:
      - title: "Materials"
        contents:
          - materials.md
          - section: "Section 1"
            contents:
              - "materials/path/to/lesson.md"
          - section: "Section 2"
            contents:
              - "materials/path/to/another.md"
              - "materials/path/to/third.md"
  ```

This is using the [metadata merging](https://quarto.org/docs/projects/quarto-projects.html#metadata-merging) feature of Quarto.

This might actually be a better alternative to automatic sidebar generation (it's more flexible and explicit)
